
export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const TASKS = "TASKS";
export const TASKS_ERROR = "TASKS_ERROR";
export const NEW_GROCERY = "GROCERY";
export const NEW_GROCERY_ERROR = "GROCERY_ERROR"
export const GET_ALL_GROCERY = "GET_ALL_GROCERY"
export const GET_ALL_GROCERY_ERROR = "GET_ALL_GROCERY_ERROR"
export const DELETE_GROCERY_ITEM_ERROR = "DELETE_GROCERY_ITEM_ERROR"
export const GET_ONE_GROCERY_LIST = "GET_ONE_GROCERY_LIST"
export const GET_ONE_GROCERY_LIST_ERROR = "GET_ONE_GROCERY_LIST_ERROR"
export const ADD_NEW_ITEM_ERROR = "ADD_NEW_ITEM_ERROR"
export const GROCERY_ITEM_LIST = "GROCERY_ITEM_LIST"
export const UPDATE_ITEM_ERROR = "UPDATE_ITEM_ERROR"
export const DELETE_ITEM_ERROR = "DELETE_ITEM_ERROR"
export const COST_SPLIT_ERROR = "COST_SPLIT_ERROR"
export const COST_SPLIT = "COST_SPLIT"
export const GET_ALL_COST_SPLIT = "GET_ALL_COST_SPLIT"
export const GET_ALL_COST_SPLIT_ERROR = "GET_ALL_COST_SPLIT_ERROR"
export const GET_ONE_GROCERY_OVERVIEW = "GET_ONE_GROCERY_OVERVIEW"
export const GET_ONE_GROCERY_OVERVIEW_ERROR = "GET_ONE_GROCERY_OVERVIEW_ERROR"

